### ISSUE TITLE
Error occurred while disabling CustomCrafting v1.6.5.1.3: NullPointerException

### ISSUE THREAD

**Issue by Kruemmelspalter** [WolfyScript/CustomCrafting-Wiki#10]
```
24.03 16:08:25 [Server] Server thread/ERROR Error occurred while disabling CustomCrafting v1.6.5.1.3 (Is it up to date?)
24.03 16:08:25 [Server] INFO java.lang.NullPointerException: null
24.03 16:08:25 [Server] INFO at me.wolfyscript.customcrafting.CustomCrafting.onDisable(CustomCrafting.java:231) ~[?:?]
24.03 16:08:25 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.dev.pluginmanager.commands.PluginManagerCommand.onCommand(PluginManagerCommand.java:329) ~[?:?]
24.03 16:08:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [custom.jar:git-Spigot-800b93f-8160e29]
24.03 16:08:25 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
24.03 16:08:25 [Server] Server thread/INFO Loading CustomCrafting v1.6.5.1.3
24.03 16:08:25 [Server] Server thread/INFO WolfyUtilities API: WolfyUtilities v1.6.3.14
24.03 16:08:25 [Server] Server thread/INFO Registering custom data
24.03 16:08:25 [Server] Server thread/ERROR null
24.03 16:08:25 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'pman' in plugin PluginManager v1.6
24.03 16:08:25 [Server] Server thread/INFO CONSOLE issued server command: /list 
24.03 16:08:32 [Multicraft] Skipped 29 lines due to rate limit (30/s)
24.03 16:08:32 [Server] Server thread/INFO ADMINKS issued server command: /pman reload WolfyUtilities
24.03 16:08:32 [Server] Server thread/INFO Disabling WolfyUtilities v1.6.3.14
24.03 16:08:32 [Server] Server thread/INFO Save stored Custom Items
24.03 16:08:33 [Server] Server thread/INFO Loading WolfyUtilities v1.6.3.14
24.03 16:08:33 [Server] Server thread/INFO Register json serializer/deserializer
24.03 16:08:34 [Server] Server thread/INFO Register Meta Setting provider
```

**Comment by WolfyScript** [comment]
It looks like CustomCrafting wasn't enabled correctly. Do you have any errors in the enable stage?

**Comment by Kruemmelspalter** [comment]
```
[14:48:24] [Server thread/INFO]: [CustomCrafting] Enabling CustomCrafting v1.6.5.1.3
[14:48:24] [Server thread/INFO]: ____ _  _ ____ ___ ____ _  _ ____ ____ ____ ____ ___ _ _  _ ____ 
[14:48:24] [Server thread/INFO]: |    |  | [__   |  |  | |\/| |    |__/ |__| |___  |  | |\ | | __ 
[14:48:24] [Server thread/INFO]: |___ |__| ___]  |  |__| |  | |___ |  \ |  | |     |  | | \| |__]
[14:48:24] [Server thread/INFO]:     v1.6.5.1.3 Free
[14:48:24] [Server thread/INFO]:  
[14:48:24] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[14:48:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:48:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:48:24] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:48:24] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.utilities.api.inventory.gui.InventoryAPI.<init>(InventoryAPI.java:45)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.customcrafting.CustomCrafting.onEnable(CustomCrafting.java:124)
[14:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[14:48:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[14:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[14:48:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[14:48:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[14:48:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267)
[14:48:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[14:48:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:48:24] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.Material.getCraftingRemainingItem()Lorg/bukkit/Material;
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.getCraftRemain(CustomItem.java:663)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:132)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:141)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:150)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.customcrafting.recipes.types.brewing.BrewingRecipe.<clinit>(BrewingRecipe.java:35)
[14:48:24] [Server thread/WARN]: 	at me.wolfyscript.customcrafting.data.CCCache.<init>(CCCache.java:79)
[14:48:24] [Server thread/WARN]: 	... 15 more
[14:48:24] [Server thread/INFO]: Special thanks to my Patrons for supporting this project: 
[14:48:24] [Server thread/INFO]:     | Nat R               | Apprehentice
[14:48:24] [Server thread/INFO]:     | Alex                | Junye Zhou
[14:48:24] [Server thread/INFO]:     | Vincent Deniau      | gizmonster
[14:48:24] [Server thread/INFO]:     | Thomas Texier       | John
[14:48:24] [Server thread/INFO]:     | HittmanA            | CypherPhyre
[14:48:24] [Server thread/INFO]:     | Alexander           | Vincent Fournier
[14:48:24] [Server thread/INFO]:     | The Hound Brothers  | Jason Asada
[14:48:24] [Server thread/INFO]:     | Inec Ackerr         | 伟铎 谢
[14:48:24] [Server thread/INFO]:     | ValentineDesigns    | Gleaks mania
[14:48:24] [Server thread/INFO]: ------------------------------------------------------------------------
[14:48:24] [Server thread/INFO]: Loaded fallback language "en_US" v5.0.0 translated by WolfyScript
[14:48:24] [Server thread/INFO]: Loaded active language "en_US" v5.0.0 translated by WolfyScript
[14:48:24] [Server thread/ERROR]: [CustomCrafting] Couldn't rename folder to the new required names!
[14:48:24] [Server thread/ERROR]: Error occurred while enabling CustomCrafting v1.6.5.1.3 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Material.getCraftingRemainingItem()Lorg/bukkit/Material;
	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.getCraftRemain(CustomItem.java:663) ~[?:?]
	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:132) ~[?:?]
	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:141) ~[?:?]
	at me.wolfyscript.utilities.api.inventory.custom_items.CustomItem.<init>(CustomItem.java:150) ~[?:?]
	at me.wolfyscript.customcrafting.handlers.ConfigHandler.loadDefaults(ConfigHandler.java:76) ~[?:?]
	at me.wolfyscript.customcrafting.CustomCrafting.onEnable(CustomCrafting.java:157) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[custom.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [custom.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [custom.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [custom.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [custom.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [custom.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [custom.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [custom.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by WolfyScript** [comment]
Please make sure you have the latest Spigot build for 1.15.2.
This method the API is using was added in later 1.15 builds.
It's best to use [BuildTools](https://www.spigotmc.org/wiki/buildtools/) to get the latest builds.
You can also use Paper, or any other Spigot-based server software.

**Comment by shambii** [comment]
Hi, i have the same problem with the plugin and i make my server with a hosting page so i cant use buildtools (i think)

**Comment by Kruemmelspalter** [comment]
You can use BuildTools on your machine to build the jar and maybe you can upload the jar to the hoster

**Comment by shambii** [comment]
if i add that in my hoster i need to change the startup parameters?

**Comment by Kruemmelspalter** [comment]
I don't think so. With the newest version everything works, so I'll close this issue
