### ISSUE TITLE
when entering the name of the craft

### ISSUE THREAD

**Issue by rkfsociety** [WolfyScript/CustomCrafting-Wiki#13]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at me.wolfyscript.customcrafting.utils.ChatUtils.getInternalNamespacedKey(ChatUtils.java:52) ~[?:?]
        at me.wolfyscript.customcrafting.gui.RecipeCreatorCluster.lambda$registerSaveButtons$10(RecipeCreatorCluster.java:161) ~[?:?]
        at me.wolfyscript.utilities.api.inventory.gui.GuiHandler.onChat(GuiHandler.java:392) ~[?:?]
        at me.wolfyscript.utilities.main.commands.InputCommand.lambda$onCommand$1(InputCommand.java:27) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-46]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-46]
        at java.lang.Thread.run(Thread.java:831) [?:?]

This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)
You are running the latest version

CustomCrafting version 1.6.6.0.1

**Comment by WolfyScript** [comment]
What exactly did you type into the chat? 
The syntax would be <namespace> <key>.

I would also recommend to use the `/wui` command as it comes with a handy tab completion.

**Comment by rkfsociety** [comment]
i do not know how to use the /wui command

**Comment by WolfyScript** [comment]
It should be simple to use. 
When you are asked to type something into the chat you open the chat, but instead of typing directly into the chat you use the command. 
So when you save a recipe `/wui <namespace> <key>`

**Comment by rkfsociety** [comment]
yes, I already managed it, I just restarted the plugin via plugman
