### ISSUE TITLE
spam to the console

### ISSUE THREAD

**Issue by rkfsociety** [WolfyScript/CustomCrafting-Wiki#14]
[00:01:58 WARN]: [CustomCrafting] Task #276 for CustomCrafting v1.6.6.0.1 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.Levelled (org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData and org.bukkit.block.data.Levelled are in unnamed module of loader 'app')
        at me.wolfyscript.customcrafting.data.cauldron.Cauldrons.lambda$new$5(Cauldrons.java:54) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1837) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.wolfyscript.customcrafting.data.cauldron.Cauldrons.lambda$new$6(Cauldrons.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-46]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-46]
        at java.lang.Thread.run(Thread.java:831) [?:?]

I can just hide it, but suddenly it's something bad...

**Comment by WolfyScript** [comment]
This is because Cauldron recipes are broken at the moment in Minecraft 1.17. It will be fixed soon!

**Comment by rkfsociety** [comment]
Well, thank you.
