### ISSUE TITLE
[CustomCrafting] Task #142 for CustomCrafting v1.6.6.0.1

### ISSUE THREAD

**Issue by EchocallingEarth** [WolfyScript/CustomCrafting-Wiki#20]
**Describe the bug**
The below error section spams the console so long as a cauldron is above a campfire. 
_[16:56:01] [Server thread/WARN]: [CustomCrafting] Task #142 for CustomCrafting v1.6.6.0.1 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData cannot be cast to class org.bukkit.block.data.Levelled (org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData and org.bukkit.block.data.Levelled are in unnamed module of loader 'app')
	at me.wolfyscript.customcrafting.data.cauldron.Cauldrons.lambda$new$5(Cauldrons.java:54) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1837) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at me.wolfyscript.customcrafting.data.cauldron.Cauldrons.lambda$new$6(Cauldrons.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1260]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1260]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1260]
	at java.lang.Thread.run(Thread.java:831) [?:?]_

**To Reproduce**
Place a cauldron over a campfire

**Expected behavior**
No error flooding console and recipes to work that require cauldron.

**Screenshots**
NA

**Server (please complete the following information):**
 - Purpur
 - Minecraft version: 1.17.1
 - Java version: 16]

**Additional context**
Plugins:
AdvancedChests, AdvancedClaimGuardian, AdvancedEnchantments, AntiCurse, Armo|
redElytra, AureliumSkills, Bank, BigDoors, BlockParticles, ChestLockGui, Chunky, Citizens, CleanroomGenerat|
or, CMI, CMIEInjector*, CMILib, ConsoleSpamFix, Core, CoreProtect, CustomCrafting, CustomEnderChest, Displa|
yShops, dtlTradersPlus, DyedBackpacks, EpicFarming, EpicFurnaces, EpicHoppers, EpicSpawners, ExoticGarden, |
ExtraGear, ExtraTools, HeadDatabase, HolographicDisplays, HorseOverhaul, ImageOnMap, InfoBook, Item-Chest-S|
orter, Jobs, LimitPillagers, Lootin, LuckPerms, LWC, Multiverse-Core, NBTAPI, NetheriteShield, NoPlugins, P|
erWorldInventory, PlaceholderAPI, ProtocolLib, PublicCrafters, Sentinel, Slimefun, spark, SuperLuckyBlock, |
SurvivalInvisiframes, Terra, UltimateCatcher, UltimateFishing, UltimateRepairing, UltimateStacker, Ultimate|
Timber, VanillaTweaks, Vault, WolfyUtilities, WorldEdit 

WolfyUtilities Version
WolfyUtilities | Core plugin API [1.15 - 1.17] 1.7.2.0

Full Log upon request.

**Comment by WolfyScript** [comment]
Fixed in CustomCrafting 1.7.1.1 https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-15-1-17-free.55883/update?update=413142
