### ISSUE TITLE
Recipe book not working

### ISSUE THREAD

**Issue by Jorc0** [WolfyScript/CustomCrafting-Wiki#24]
**Describe the bug**
My recipe book isnt working, tried lots of things, changed lots of things, restarted a few times, nothing worked.
groups are shown, but recipes wont

**To Reproduce**
1. Go to '/recipes'
2. Click on 'Recipe group'

**Expected behavior**
Recipes should show up (wont)

**Screenshots**
![image](https://user-images.githubusercontent.com/48130077/125868654-4477966f-9e62-4e86-9276-871147cf3ea4.png)
![image](https://user-images.githubusercontent.com/48130077/125868669-5b9e1b01-7be0-4392-8b2e-5d76173ffee2.png)

**Server:**
 - Server Software  purpurclip-1.17-1255.jar
 - Minecraft version 1.17
 - Java version [e.g. Java 8, 11, 16] 16
 - WolfyUtilities version wolfyutilities-1.7.2.0.jar
 - CustomCrafting version customcrafting-spigot-1.7.1.1f.jar

**Additional context**
https://anonfiles.com/zcS2J76cu3/recipe_book_1_json

**Comment by WolfyScript** [comment]
It might be because you have no filter set.
```json
"filters" : {
    "sort" : [ ],
    "options" : [ {
      "id" : "search",
      "icon" : "COMPASS",
      "name" : "$recipe_book.filter.search.name$",
      "description" : [ ],
      "groups" : [ ],
      "namespaces" : [ ],
      "recipes" : [ ],
      "creativeModeTabs" : [ "SEARCH" ],
      "materials" : [ ]
    } ]
}
```
No sure if that is how it should work. I might change it so that if you set no filter, it displays everything.

**Comment by Jorc0** [comment]
> It might be because you have no filter set.
> 
> ```json
> "filters" : {
>     "sort" : [ ],
>     "options" : [ {
>       "id" : "search",
>       "icon" : "COMPASS",
>       "name" : "$recipe_book.filter.search.name$",
>       "description" : [ ],
>       "groups" : [ ],
>       "namespaces" : [ ],
>       "recipes" : [ ],
>       "creativeModeTabs" : [ "SEARCH" ],
>       "materials" : [ ]
>     } ]
> }
> ```
> 
> No sure if that is how it should work. I might change it so that if you set no filter, it displays everything.

But do i really need to set up filters?

**Comment by Jorc0** [comment]
Might have found the issue

```[11:49:03 INFO]: Jorc0 issued server command: /cc reload
[11:49:03 INFO]: [CustomCrafting] Loaded fallback language "en_US" v5.0.0 translated by WolfyScript
[11:49:03 INFO]: [CustomCrafting] Loaded active language "en_US" v5.0.0 translated by WolfyScript
[11:49:03 INFO]: [CustomCrafting] Loading Recipes & Items
[11:49:03 INFO]: [CustomCrafting] - - - - [Local Storage] - - - -
[11:49:03 INFO]: [CustomCrafting] > customcrafting
[11:49:03 INFO]: [CustomCrafting] > vip
[11:49:03 INFO]: [CustomCrafting] > protes
[11:49:03 INFO]: [CustomCrafting] 
[11:49:03 INFO]: [CustomCrafting] Indexing Recipe Book...
[11:49:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'cc reload' in me.wolfyscript.customcrafting.commands.CommandCC(customcrafting)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[patched_1.17.jar:git-Purpur-1255]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2127) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2108) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1414) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1392) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1361) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1272) ~[patched_1.17.jar:git-Purpur-1255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1255]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.wolfyscript.utilities.util.NamespacedKey.getNamespace()" 
because the return value of "me.wolfyscript.customcrafting.configs.recipebook.RecipeContainer.getRecipe()" is null
        at me.wolfyscript.customcrafting.configs.recipebook.CategoryFilter.filter(CategoryFilter.java:61) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at me.wolfyscript.customcrafting.configs.recipebook.Category.indexFilters(Category.java:54) ~[?:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1067) ~[?:?]
        at me.wolfyscript.customcrafting.configs.recipebook.Categories.lambda$index$0(Categories.java:114) ~[?:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1067) ~[?:?]
        at me.wolfyscript.customcrafting.configs.recipebook.Categories.index(Categories.java:112) ~[?:?]
        at me.wolfyscript.customcrafting.commands.cc_subcommands.ReloadSubCommand.onCommand(ReloadSubCommand.java:37) ~[?:?]
        at me.wolfyscript.customcrafting.commands.IndexCommand.execute(IndexCommand.java:32) ~[?:?]
        at me.wolfyscript.customcrafting.commands.CommandCC.execute(CommandCC.java:37) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.jar:git-Purpur-1255]
        ... 20 more```

**Comment by WolfyScript** [comment]
Ok, I found the issue causing this issue and I will fix it.
To fix this right now, try to remove the group `"protes"` so it is like `"groups": [ ]`.

**Comment by Jorc0** [comment]
The error on console is fixed, but recipes keep not showing up

**Comment by Jorc0** [comment]
Found another error, but cant manage what file is it from

```
[11:52:52 INFO]: [CustomCrafting] Loaded active language "en_US" v5.0.0 translated by WolfyScript
[11:52:52 WARN]: me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting double-quote to start field name
[11:52:52 WARN]:  at [Source: (File); line: 24, column: 2]
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:2049)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1700)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1038)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4453)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2806)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1829)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.configs.recipebook.Categories$Deserializer.deserialize(Categories.java:165)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.configs.recipebook.Categories$Deserializer.deserialize(Categories.java:153)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
[11:52:52 WARN]:        at me.wolfyscript.utilities.libraries.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3299)
[11:52:52 WARN]:        at me.wolfyscript.utilities.api.config.JsonConfig.lambda$new$0(JsonConfig.java:74)
[11:52:52 WARN]:        at me.wolfyscript.utilities.api.config.JsonConfig.load(JsonConfig.java:235)
[11:52:52 WARN]:        at me.wolfyscript.utilities.api.config.JsonConfig.load(JsonConfig.java:203)
[11:52:52 WARN]:        at me.wolfyscript.utilities.api.config.JsonConfig.<init>(JsonConfig.java:44)
[11:52:52 WARN]:        at me.wolfyscript.utilities.api.config.JsonConfig.<init>(JsonConfig.java:72)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.configs.recipebook.RecipeBookConfig.<init>(RecipeBookConfig.java:11)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.handlers.ConfigHandler.loadRecipeBookConfig(ConfigHandler.java:129)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.commands.cc_subcommands.ReloadSubCommand.onCommand(ReloadSubCommand.java:33)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.commands.IndexCommand.execute(IndexCommand.java:32)
[11:52:52 WARN]:        at me.wolfyscript.customcrafting.commands.CommandCC.execute(CommandCC.java:37)
[11:52:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[11:52:52 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[11:52:52 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2316)
[11:52:52 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2127)
[11:52:52 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[11:52:52 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[11:52:52 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[11:52:52 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[11:52:52 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:52:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[11:52:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1414)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[11:52:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1392)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1385)
[11:52:52 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1361)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1272)
[11:52:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11:52:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[11:52:52 INFO]: [CustomCrafting] Loading Recipes & Items```
