### ISSUE TITLE
error wolfyutilities

### ISSUE THREAD

**Issue by mihalera** [WolfyScript/CustomCrafting-Wiki#42]
1.17.1 paper git 170
latest version plugins wolfyscript

[21:31:54] [Server thread/ERROR]: null
--
934 | org.bukkit.command.CommandException: Unhandled exception executing 'customcrafting:recipes' in me.wolfyscript.customcrafting.commands.CommandRecipe(recipes)
935 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[minecraft_server.jar:git-Paper-170]
936 | at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[minecraft_server.jar:git-Paper-170]
937 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[app:?]
938 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[app:?]
939 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[app:?]
940 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
941 | at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
942 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[app:?]
943 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft_server.jar:git-Paper-170]
944 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
945 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
946 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[minecraft_server.jar:git-Paper-170]
947 | at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[minecraft_server.jar:git-Paper-170]
948 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
949 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[minecraft_server.jar:git-Paper-170]
950 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[minecraft_server.jar:git-Paper-170]
951 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
952 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[minecraft_server.jar:git-Paper-170]
953 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[minecraft_server.jar:git-Paper-170]
954 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[minecraft_server.jar:git-Paper-170]
955 | at java.lang.Thread.run(Thread.java:831) [?:?]
956 | Caused by: java.lang.IllegalStateException: zip file closed
957 | at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
958 | at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
959 | at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
960 | at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
961 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[minecraft_server.jar:git-Paper-170]
962 | at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
963 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[minecraft_server.jar:git-Paper-170]
964 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[minecraft_server.jar:git-Paper-170]
965 | at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
966 | at me.wolfyscript.customcrafting.utils.ChatUtils.checkPerm(ChatUtils.java:35) ~[customcrafting-spigot-1.7.1.1f.jar:?]
967 | at me.wolfyscript.customcrafting.utils.ChatUtils.checkPerm(ChatUtils.java:31) ~[customcrafting-spigot-1.7.1.1f.jar:?]
968 | at me.wolfyscript.customcrafting.commands.CommandRecipe.execute(CommandRecipe.java:38) ~[customcrafting-spigot-1.7.1.1f.jar:?]
969 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[minecraft_server.jar:git-Paper-170]
970 | ... 20 more

**Comment by mihalera** [comment]
If you disable one plugin, then everything works
