### ISSUE TITLE
Brewing Stand fails to brew custom potions

### ISSUE THREAD

**Issue by TZTGa** [WolfyScript/CustomCrafting-Wiki#71]
**Describe the bug**
I created a custom recipe for brewing stands but it didn't work.

**The code**
`{
  "group" : "",
  "hidden" : false,
  "priority" : "NORMAL",
  "exactItemMeta" : true,
  "conditions" : [ {
    "id" : "world_name",
    "option" : "IGNORE",
    "names" : [ ]
  }, {
    "id" : "craft_limit",
    "option" : "IGNORE",
    "limit" : 0
  }, {
    "id" : "world_biome",
    "option" : "IGNORE",
    "biomes" : [ ]
  }, {
    "id" : "world_time",
    "option" : "IGNORE",
    "time" : 0
  }, {
    "id" : "weather",
    "option" : "IGNORE",
    "weather" : "NONE"
  }, {
    "id" : "permission",
    "option" : "IGNORE",
    "permission" : "customcrafting.craft.%namespace%.%recipe_name%"
  }, {
    "id" : "elite_crafting_table",
    "option" : "IGNORE",
    "elite_crafting_tables" : [ ]
  }, {
    "id" : "advanced_workbench",
    "option" : "IGNORE"
  }, {
    "id" : "player_experience",
    "option" : "IGNORE",
    "experience" : 0
  }, {
    "id" : "craft_delay",
    "option" : "IGNORE",
    "delay" : 0
  } ],
  "ingredients" : {
    "items" : [ {
      "custom_amount" : 1,
      "wolfyutilities" : "customcrafting:potion/atavistic_orb"
    } ],
    "tags" : [ ]
  },
  "fuel_cost" : 1,
  "brew_time" : 400,
  "allowed_items" : {
    "items" : [ {
      "custom_amount" : 1,
      "wolfyutilities" : "customcrafting:potion/powerful_potion"
    } ],
    "tags" : [ ]
  },
  "results" : {
    "items" : [ {
      "custom_amount" : 1,
      "wolfyutilities" : "customcrafting:potion/atavistic_potion"
    } ],
    "tags" : [ ],
    "extensions" : [ ]
  },
  "duration_change" : 0,
  "amplifier_change" : 0,
  "reset_effects" : false,
  "color" : null,
  "effect_removals" : [ ],
  "effect_additions" : [ ],
  "effect_upgrades" : [ ],
  "required_effects" : [ ]
}`

The Log Output
`[05:00:33 WARN]: [CustomCrafting] Task #1812 for CustomCrafting v1.7.1.3 generated an exception
java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_17_R1.block.CraftBrewingStand: method 'void <init>(org.bukkit.block.Block)' not found
	at me.wolfyscript.utilities.api.nms.v1_17_R1_P1.block.NMSBrewingStand.<init>(NMSBrewingStand.java:9) ~[wolfyutilities-1.7.3.0.jar:?]
	at me.wolfyscript.utilities.api.nms.v1_17_R1_P1.BlockUtilImpl.getNmsBrewingStand(BlockUtilImpl.java:16) ~[wolfyutilities-1.7.3.0.jar:?]
	at me.wolfyscript.customcrafting.listeners.BrewingStandListener.lambda$onInv$4(BrewingStandListener.java:94) ~[customcrafting-spigot-1.7.1.3f.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[minecraft_server.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[minecraft_server.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]`
**Screenshots**
![image](https://user-images.githubusercontent.com/92923886/138357473-692dfaab-0f70-4c6e-86b1-5d70ea824bae.png)

**Server (please complete the following information):**
 - Server Software Spigot
 - Minecraft version 1.17.1
 - Java version 16

**Additional context**

**Comment by TZTGa** [comment]
To clarify,the bottles are Awkward Potions, the expected result is the potion the mouse was pointing to. Thx!

**Comment by WolfyScript** [comment]
You can not create custom potion ingredients that are the same as the vanilla ones. 
So no gunpowder, glowstone dust, sugar, etc.

Looks like I should implement a limit in the GUI to prevent such items from being added.

**Comment by TZTGa** [comment]
Thanks!

**Comment by TZTGa** [comment]
It didnt work this time despite I used no Vanilla ingredients.
Screenshot:
![image](https://user-images.githubusercontent.com/92923886/138517455-2c14340a-091a-42a5-84b8-0328b1267436.png)

The same warning
[04:14:14 WARN]: [CustomCrafting] Task #178 for CustomCrafting v1.7.1.3 generated an exception
java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_17_R1.block.CraftBrewingStand: method 'void <init>(org.bukkit.block.Block)' not found
	at me.wolfyscript.utilities.api.nms.v1_17_R1_P1.block.NMSBrewingStand.<init>(NMSBrewingStand.java:9) ~[wolfyutilities-1.7.3.0.jar:?]
	at me.wolfyscript.utilities.api.nms.v1_17_R1_P1.BlockUtilImpl.getNmsBrewingStand(BlockUtilImpl.java:16) ~[wolfyutilities-1.7.3.0.jar:?]
	at me.wolfyscript.customcrafting.listeners.BrewingStandListener.lambda$onInv$4(BrewingStandListener.java:94) ~[customcrafting-spigot-1.7.1.3f.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[minecraft_server.jar:git-Paper-349]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[minecraft_server.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[minecraft_server.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by TZTGa** [comment]
Code in data
{
  "group" : "",
  "hidden" : false,
  "priority" : "NORMAL",
  "exactItemMeta" : true,
  "conditions" : [ {
    "id" : "world_name",
    "option" : "IGNORE",
    "names" : [ ]
  }, {
    "id" : "craft_limit",
    "option" : "IGNORE",
    "limit" : 0
  }, {
    "id" : "world_biome",
    "option" : "IGNORE",
    "biomes" : [ ]
  }, {
    "id" : "world_time",
    "option" : "IGNORE",
    "time" : 0
  }, {
    "id" : "weather",
    "option" : "IGNORE",
    "weather" : "NONE"
  }, {
    "id" : "permission",
    "option" : "IGNORE",
    "permission" : "customcrafting.craft.%namespace%.%recipe_name%"
  }, {
    "id" : "elite_crafting_table",
    "option" : "IGNORE",
    "elite_crafting_tables" : [ ]
  }, {
    "id" : "advanced_workbench",
    "option" : "IGNORE"
  }, {
    "id" : "player_experience",
    "option" : "IGNORE",
    "experience" : 0
  }, {
    "id" : "craft_delay",
    "option" : "IGNORE",
    "delay" : 0
  } ],
  "ingredients" : {
    "items" : [ {
      "custom_amount" : 1,
      "wolfyutilities" : "customcrafting:potion/atavistic_orb"
    } ],
    "tags" : [ ],
    "replaceWithRemains" : true
  },
  "fuel_cost" : 1,
  "brew_time" : 400,
  "allowed_items" : {
    "items" : [ {
      "custom_amount" : 1,
      "wolfyutilities" : "customcrafting:potion/effective_potion"
    } ],
    "tags" : [ ],
    "replaceWithRemains" : true
  },
  "results" : {
    "items" : [ {
      "custom_amount" : 1,
      "wolfyutilities" : "customcrafting:potion/atavistic_potion"
    } ],
    "tags" : [ ],
    "extensions" : [ ]
  },
  "duration_change" : 0,
  "amplifier_change" : 0,
  "reset_effects" : false,
  "color" : null,
  "effect_removals" : [ ],
  "effect_additions" : [ ],
  "effect_upgrades" : [ ],
  "required_effects" : [ ]
}

**Comment by WolfyScript** [comment]
Ah ok... that issue is because of some changes internally in Bukkit. Next 2.16 update will fix this. So for now you are not able to use BrewingRecipes.

**Comment by TZTGa** [comment]
OK, Thanks a lot! I look forward to your brilliant update!
