### ISSUE TITLE
Error loading [CC]

### ISSUE THREAD

**Issue by AcesGamingUK** [WolfyScript/CustomCrafting-Wiki#8]
<details>
  <summary>Error</summary>
  Could not load 'plugins\customcrafting.jar' in folder 'plugins'
  
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/wolfyscript/utilities/util/Keyed
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-465]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-465]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-465]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-465]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-465]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-465]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-465]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoClassDefFoundError: me/wolfyscript/utilities/util/Keyed
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:468) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-465]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-465]
... 7 more
Caused by: java.lang.ClassNotFoundException: me.wolfyscript.utilities.util.Keyed
at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-465]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-465]
at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:468) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-465]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-465]
... 7 more
  </details>

> CustomCrafting version - `1.6.5.0`
> WolfyUtilities Version - `1.6.3.6`
> Server Version - `Paper version git-Paper-465 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

**Comment by AcesGamingUK** [comment]
suddenly started working :/ issue resolved
